### PR TITLE
samples: update sample to use protos, until typing can be fixed

### PR DESCRIPTION
**Pull request by juffalow**
Function `searchUris` takes an object with `uri` field which is a string and a `threatTypes` field which is array of numbers, not strings.

If strings are used, it will show error:

```
Argument of type '{ uri: string; threatTypes: string[]; }' is not assignable to parameter of type 'ISearchUrisRequest'.
```

Because `searchUris` first parameters is of type `protos.google.cloud.webrisk.v1.ISearchUrisRequest`:

```ts
interface ISearchUrisRequest {

    /** SearchUrisRequest uri */
    uri?: (string|null);

    /** SearchUrisRequest threatTypes */
    threatTypes?: (google.cloud.webrisk.v1.ThreatType[]|null);
}
```

And `google.cloud.webrisk.v1.ThreatType` is:

```ts
enum ThreatType {
    THREAT_TYPE_UNSPECIFIED = 0,
    MALWARE = 1,
    SOCIAL_ENGINEERING = 2,
    UNWANTED_SOFTWARE = 3
}
```

Even in [web_risk_service_client.ts](./src/v1/web_risk_service_client.ts) it is declared as:

```js
  /**
   * ...
   * @param {number[]} request.threatTypes
   * ...
   */
  searchUris()
```

### CODE REVIEW

**Comment by chingor13** [comment]
This is a bug in our generated types. We want to be able to accept the stringified versions of the enums which are more friendly.

Filed https://github.com/googleapis/gax-nodejs/issues/1205 on our types generator

**Comment by sofisl** [comment]
Thanks @chingor13. In the meantime, I think it makes sense to update the sample. @juffalow, the README is generated from the quickstart. Could you make these changes to samples/quickstart, and the changes will propagate to the README? Thanks.

**Comment by juffalow** [comment]
Thank @sofisl! I updated the code in `samples/quickstart.js` and dropped the old commit.

**Comment by sofisl** [comment]
Sorry, one more request, would you mind adding a TODO comment on the sample like so (above the START tag):
```TODO: revert threat types to strings once https://github.com/googleapis/gax-nodejs/issues/1205 is fixed```

**Comment by juffalow** [comment]
Hi @sofisl! I added there the comment. Hope this is the place you mentioned.

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@juffalow thank you for the contribution 👏

**Pull request merged**
